name: Dotfiles PR Issue Generator

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number in dotfiles repo to analyze'
        required: true
      trigger_type:
        description: 'When to trigger (created, updated, merged)'
        required: true
        default: 'merged'
        type: choice
        options:
          - created
          - updated
          - merged
  repository_dispatch:
    types: [dotfiles-pr-event]

jobs:
  generate-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tech-skills-gym repo
        uses: actions/checkout@v3
        
      - name: Setup GitHub CLI
        uses: cli/setup-gh@v1
        
      - name: Get PR details
        id: pr-details
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "PR_NUMBER=${{ github.event.client_payload.pr_number }}" >> $GITHUB_ENV
            echo "TRIGGER_TYPE=${{ github.event.client_payload.trigger_type }}" >> $GITHUB_ENV
          else
            echo "PR_NUMBER=${{ github.event.inputs.pr_number }}" >> $GITHUB_ENV
            echo "TRIGGER_TYPE=${{ github.event.inputs.trigger_type }}" >> $GITHUB_ENV
          fi
      
      - name: Fetch PR details from dotfiles repo
        id: fetch-pr
        run: |
          # Get PR data using GitHub CLI
          PR_JSON=$(gh pr view ${{ env.PR_NUMBER }} --repo atxtechbro/dotfiles --json title,url,author,createdAt,updatedAt,mergedAt,mergedBy,body,baseRefName,headRefName,state,merged)
          
          # Check if PR exists (gh will exit with error if PR doesn't exist)
          if [ $? -ne 0 ]; then
            echo "::error::PR #${{ env.PR_NUMBER }} not found in atxtechbro/dotfiles repository"
            exit 1
          fi
          
          # Extract PR details
          echo "PR_TITLE=$(echo $PR_JSON | jq -r .title)" >> $GITHUB_ENV
          echo "PR_URL=$(echo $PR_JSON | jq -r .url)" >> $GITHUB_ENV
          echo "PR_AUTHOR=$(echo $PR_JSON | jq -r .author.login)" >> $GITHUB_ENV
          echo "PR_CREATED_AT=$(echo $PR_JSON | jq -r .createdAt)" >> $GITHUB_ENV
          echo "PR_UPDATED_AT=$(echo $PR_JSON | jq -r .updatedAt)" >> $GITHUB_ENV
          echo "PR_MERGED_AT=$(echo $PR_JSON | jq -r .mergedAt)" >> $GITHUB_ENV
          echo "PR_MERGED_BY=$(echo $PR_JSON | jq -r '.mergedBy.login // "N/A"')" >> $GITHUB_ENV
          echo "PR_DESCRIPTION=$(echo $PR_JSON | jq -r .body)" >> $GITHUB_ENV
          echo "PR_BASE_BRANCH=$(echo $PR_JSON | jq -r .baseRefName)" >> $GITHUB_ENV
          echo "PR_HEAD_BRANCH=$(echo $PR_JSON | jq -r .headRefName)" >> $GITHUB_ENV
          echo "PR_STATE=$(echo $PR_JSON | jq -r .state)" >> $GITHUB_ENV
          echo "PR_MERGED=$(echo $PR_JSON | jq -r .merged)" >> $GITHUB_ENV
          
          # Check if we should proceed based on trigger type
          if [ "${{ env.TRIGGER_TYPE }}" == "merged" ] && [ "$(echo $PR_JSON | jq -r .merged)" != "true" ]; then
            echo "Skipping because PR is not merged yet and trigger type is 'merged'"
            echo "SHOULD_PROCEED=false" >> $GITHUB_ENV
            exit 0
          else
            echo "SHOULD_PROCEED=true" >> $GITHUB_ENV
          fi
          
          # Create a sanitized ID for the issue
          ISSUE_ID=$(echo "${{ env.PR_NUMBER }}-$(echo $PR_JSON | jq -r .title)" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV
      
      - name: Check if we should proceed
        if: env.SHOULD_PROCEED != 'true'
        run: |
          echo "Skipping issue creation based on trigger conditions"
          exit 0
      
      - name: Get PR diff
        id: get-diff
        run: |
          # Get PR diff using GitHub CLI
          PR_DIFF=$(gh pr diff ${{ env.PR_NUMBER }} --repo atxtechbro/dotfiles)
          
          echo "PR_DIFF<<EOF" >> $GITHUB_ENV
          echo "$PR_DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Get PR files
        id: get-files
        run: |
          # Get files changed using GitHub CLI
          PR_FILES_JSON=$(gh pr view ${{ env.PR_NUMBER }} --repo atxtechbro/dotfiles --json files)
          
          # Format files list
          FILES_LIST=$(echo $PR_FILES_JSON | jq -r '.files[] | "- **" + .path + "** (" + .status + ", " + (.additions + .deletions | tostring) + " changes)"')
          
          echo "FILES_LIST<<EOF" >> $GITHUB_ENV
          echo "$FILES_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          # Get raw file contents for each file
          echo "FILE_CONTENTS<<EOF" >> $GITHUB_ENV
          echo $PR_FILES_JSON | jq -r '.files[] | select(.status != "removed") | "### " + .path + "\n\n```\n"' | while read -r line; do
            if [[ $line == \#\#\#* ]]; then
              echo "$line"
              # Extract filename from the line
              FILENAME=$(echo "$line" | sed 's/### //')
              # Skip to next iteration
              continue
            elif [[ $line == \`\`\`* ]]; then
              echo '```'
              # Get file content from the PR head branch
              if [ -n "$FILENAME" ]; then
                gh api repos/atxtechbro/dotfiles/contents/$FILENAME?ref=${{ env.PR_HEAD_BRANCH }} --jq '.content' | base64 -d
                echo ""
                echo '```'
                FILENAME=""
              fi
            fi
          done
          echo "EOF" >> $GITHUB_ENV
      
      - name: Get PR comments
        id: get-comments
        run: |
          # Get PR comments using GitHub CLI
          PR_COMMENTS_JSON=$(gh pr view ${{ env.PR_NUMBER }} --repo atxtechbro/dotfiles --json comments)
          
          # Format comments
          COMMENTS_LIST=$(echo $PR_COMMENTS_JSON | jq -r '.comments[] | "### Comment by " + .author.login + " at " + .createdAt + "\n\n" + .body + "\n"')
          
          echo "COMMENTS_LIST<<EOF" >> $GITHUB_ENV
          echo "$COMMENTS_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Get PR commits
        id: get-commits
        run: |
          # Get PR commits using GitHub CLI
          PR_COMMITS_JSON=$(gh pr view ${{ env.PR_NUMBER }} --repo atxtechbro/dotfiles --json commits)
          
          # Format commits
          COMMITS_LIST=$(echo $PR_COMMITS_JSON | jq -r '.commits[] | "- **" + .committedDate + "**: " + .messageHeadline')
          
          echo "COMMITS_LIST<<EOF" >> $GITHUB_ENV
          echo "$COMMITS_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Check for existing issue
        id: check-issue
        run: |
          # Search for issues with our PR number in the title
          ISSUES_JSON=$(gh issue list --repo ${{ github.repository }} --search "in:title Dotfiles PR #${{ env.PR_NUMBER }}" --json number,title)
          
          ISSUE_COUNT=$(echo $ISSUES_JSON | jq '. | length')
          
          if [ "$ISSUE_COUNT" -gt "0" ]; then
            ISSUE_NUMBER=$(echo $ISSUES_JSON | jq -r '.[0].number')
            echo "ISSUE_EXISTS=true" >> $GITHUB_ENV
            echo "EXISTING_ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
          else
            echo "ISSUE_EXISTS=false" >> $GITHUB_ENV
          fi
      
      - name: Create or update issue
        run: |
          # Prepare issue body
          cat > issue_body.md << EOL
          # Dotfiles PR #${{ env.PR_NUMBER }}: ${{ env.PR_TITLE }}

          This issue contains data from [PR #${{ env.PR_NUMBER }}](${{ env.PR_URL }}) in the dotfiles repository.

          ## PR Metadata

          - **Author:** ${{ env.PR_AUTHOR }}
          - **Created:** ${{ env.PR_CREATED_AT }}
          - **Updated:** ${{ env.PR_UPDATED_AT }}
          - **Merged:** ${{ env.PR_MERGED_AT }}
          - **Merged by:** ${{ env.PR_MERGED_BY }}
          - **Base branch:** ${{ env.PR_BASE_BRANCH }}
          - **Head branch:** ${{ env.PR_HEAD_BRANCH }}

          ## PR Description

          ${{ env.PR_DESCRIPTION }}

          ## Files Changed

          ${{ env.FILES_LIST }}

          ## Commits

          ${{ env.COMMITS_LIST }}

          ## Comments

          ${{ env.COMMENTS_LIST }}

          ## File Contents

          ${{ env.FILE_CONTENTS }}

          ## Diff

          \`\`\`diff
          ${{ env.PR_DIFF }}
          \`\`\`

          ---

          <details>
          <summary>Learning Module Template</summary>

          # Learning Module: ${{ env.PR_TITLE }}

          ## Overview
          <!-- What do these dotfile changes accomplish? Why are they valuable? -->

          ## Key Concepts
          <!-- List 3-5 technical concepts that are important to understand -->

          ## Learning Objectives
          <!-- Create 3-5 specific learning objectives -->

          ## Technical Explanation
          <!-- Provide a detailed explanation of what the changes do and how they work -->

          ## Practice Exercises
          <!-- Create 3-5 hands-on exercises to help understand these changes better -->

          ## Resources
          <!-- Suggest 3-5 resources (documentation, tutorials, etc.) for deeper learning -->

          </details>
          EOL
          
          if [ "${{ env.ISSUE_EXISTS }}" == "true" ]; then
            # Update existing issue
            gh issue edit ${{ env.EXISTING_ISSUE_NUMBER }} --body-file issue_body.md --repo ${{ github.repository }}
            echo "Updated issue #${{ env.EXISTING_ISSUE_NUMBER }}"
          else
            # Create new issue
            gh issue create --title "Dotfiles PR #${{ env.PR_NUMBER }}: ${{ env.PR_TITLE }}" --body-file issue_body.md --repo ${{ github.repository }}
            echo "Created new issue"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
